jenkins_plugins:
  port: 8080
  cli_dest: '/var/lib/jenkins/jenkins-cli.jar' # Jenkins CLI destination
  updates_dest: '/var/lib/jenkins/updates_jenkins.json' # Jenkins updates file

  # list of jenkins plugins to be installed on the jenkins box
  plugins: [
    { name: 'ruby-runtime', version: '0.12'},
    { name: 'dashboard-view', version: '2.9.5'},
    { name: 'antisamy-markup-formatter', version: '1.3'},
    { name: 'github-api', version: '1.67'},
    { name: 'ansicolor', version: '0.4.1'},
    { name: 'external-monitor-job', version: '1.4'},
    { name: 'build-with-parameters', version: '1.3'},
    { name: 'build-environment', version: '1.4'},
    { name: 'pam-auth', version: '1.2'},
    { name: 'delivery-pipeline-plugin', version: '0.8.7'},
    { name: 'conditional-buildstep', version: '1.3.3'},
    { name: 'mailer', version: '1.12'},
    { name: 'junit', version: '1.3'},
    { name: 'locks-and-latches', version: '0.6'},
    { name: 'ircbot', version: '2.26'},
    { name: 'github', version: '1.11.3'},
    { name: 'ldap', version: '1.11'},
    { name: 'nodejs', version: '0.2.1'},
    { name: 'notification', version: '1.9'},
    { name: 'jquery', version: '1.7.2-1'},
    { name: 'windows-slaves', version: '1.0'},
    { name: 'timestamper', version: '1.5.14'},
    { name: 'linenumbers', version: '1.1'},
    { name: 'mapdb-api', version: '1.0.6.0'},
    { name: 'config-autorefresh-plugin', version: '1.0'},
    { name: 'ant', version: '1.2'},
    { name: 'ssh', version: '2.4'},
    { name: 'publish-over-ssh', version: '1.12'},
    { name: 'scm-api', version: '0.2'},
    { name: 'multiple-scms', version: '0.4'},
    { name: 'buildgraph-view', version: '1.1.1'},
    { name: 'ssh-credentials', version: '1.10'},
    { name: 'log-parser', version: '1.0.8'},
    { name: 'show-build-parameters', version: '1.0'},
    { name: 'ci-game', version: '1.20'},
    { name: 'naginator', version: '1.13'},
    { name: 'jobConfigHistory', version: '2.10'},
    { name: 'javadoc', version: '1.3'},
    { name: 'throttle-concurrents', version: '1.8.4'},
    { name: 'build-flow-plugin', version: '0.17'},
    { name: 'copyartifact', version: '1.32.1'},
    { name: 'mask-passwords', version: '2.7.2'},
    { name: 'token-macro', version: '1.10'},
    { name: 'envinject', version: '1.91.1'},
    { name: 'analysis-core', version: '1.65'},
    { name: 'flexible-publish', version: '0.13'},
    { name: 'greenballs', version: '1.14'},
    { name: 'build-pipeline-plugin', version: '1.4.5'},
    { name: 'maven-plugin', version: '2.8'},
    { name: 'ssh-slaves', version: '1.9'},
    { name: 'matrix-project', version: '1.4'},
    { name: 'git', version: '2.3.5'},
    { name: 'git-parameter', version: '0.4.0'},
    { name: 'git-client', version: '1.12.0'},
    { name: 'credentials', version: '1.18'},
    { name: 'gitlab-hook', version: '1.1.0'},
    { name: 'matrix-auth', version: '1.2'},
    { name: 'run-condition', version: '1.0'},
    { name: 'ssh-agent', version: '1.5'},
    { name: 'ghprb', version: '1.18'},
    { name: 'groovy', version: '1.25'},
    { name: 'github-oauth', version: '0.20'},
    { name: 'rebuild', version: '1.22'},
    { name: 'configurationslicing', version: '1.40'},
    { name: 'parameterized-trigger', version: '2.26'},
    { name: 'build-timeout', version: '1.14'},
    { name: 'job-dsl', version: '1.26'},
    { name: 'subversion', version: '2.4.5'},
    { name: 'email-ext', version: '2.40.2'},
    { name: 'gatling', version: '1.1.0'},
    { name: 'sonar', version: '2.1'},
    { name: 'gerrit-trigger', version: '2.14.0'},
    { name: 'job-log-logger-plugin', version: '1.0'},
    { name: 'translation', version: '1.12'} ]